grails-app/domain/projet/grails/mbds/esatic/Annonce.groovy
package projet.grails.mbds.esatic

class Annonce {

    String  title
    String  description
    Float   price
    Boolean status
    Date    dateCreated
    Date    lastUpdated
    List    illustrations

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title nullable: false, blank: false, size: 3..50
        description nullable: false, blank: false
        price nullable: false, min: 0F
        status nullable: false
    }

    static mapping = {
        description type: 'text'
    }
}

grails-app/controllers/projet/grails/mbds/esatic/AnnonceController.groovy
package projet.grails.mbds.esatic

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured('ROLE_ADMIN')
class AnnonceController {

    AnnonceService annonceService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 1000, 10000)
        respond annonceService.list(params), model:[annonceCount: annonceService.count()]
    }

    def show(Long id) {
        respond annonceService.get(id)
    }

    def create() {
        respond new Annonce(params)
    }

    def save(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond annonceService.get(id)
    }

    def update(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*'{ respond annonce, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        annonceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
<g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<link rel="icon" type="image/x-icon" href="../assets/img/favicon.ico"/>
<link href="../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/plugins.css" rel="stylesheet" type="text/css" />
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
<!-- END GLOBAL MANDATORY STYLES -->

<!--  BEGIN CUSTOM STYLE FILE  -->
<link href="../assets/css/ecommerce/addedit_categories.css" rel="stylesheet" type="text/css">

<link rel="icon" type="image/x-icon" href="../assets/img/favicon.ico"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
<link href="../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/plugins.css" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->

<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="../assets/plugins/mdl/material.css">
</head>


<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Ajout d'une annonce</h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area add-category">
                <div class="row">
                    <div class="mx-xl-auto col-xl-10 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Annonce</span></h2></div>

                            <div class="card-body">
                                <div class="card-body">
                                    <form action="/annonce/save" method="post" >


                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Title :</label>
                                                <div class="col-md-8">
                                                    <input class="form-control" value="" required="" id="title" name="title" type="text">
                                                </div>
                                            </div>
                                        </div>



                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Description :</label>
                                                <div class="col-md-8">
                                                    <textarea class="form-control" rows="5" cols="5" id="desciption" value="" name="description"></textarea>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Price :</label>
                                                <div class="col-md-8">
                                                    <input class="form-control" type="number decimal" id="price"  required="" value="" id="price" name="price" type="text">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-xl-4 col-lg-6 col-sm-6  layout-spacing">
                                        <div class="statbox widget box box-shadow">

                                            <div class="widget-content widget-content-area">
                                                <div class="mb-4">

                                                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">
                                                        <input type="hidden"  name="_status" />
                                                        <input type="checkbox"name="status" id="checkbox-1" class="mdl-checkbox__input" checked>
                                                        <span class="mdl-checkbox__label">Status</span>
                                                    </label>

                                                </div>
                                            </div>
                                        </div>
                                        </div>

                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Author :</label>

                                                <div class="col-md-8">
                                                     <g:select class="form-control form-custom mb-4" name="author" from="${projet.grails.mbds.esatic.User.getAll()}" optionKey="id" optionValue="username"/>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group mb-4">
                                            <label for='illustrations'>Illustrations</label><ul></ul><a href="/illustration/create?annonce.id=">Ajouter une  Illustration</a>
                                        </div>
                                 <fieldset class="buttons">
                                     <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                                 </fieldset>
                                    </form>




                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="../assets/js/libs/jquery-3.1.1.min.js"></script>
<script src="../assets/js/loader.js"></script>
<script src="../assets/bootstrap/js/popper.min.js"></script>
<script src="../assets/bootstrap/js/bootstrap.min.js"></script>
<script src="../assets/plugins/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="../assets/plugins/blockui/jquery.blockUI.min.js"></script>
<script src="../assets/js/app.js"></script>

<script>
    $(document).ready(function() {
        App.init();
    });
</script>
<script src="../assets/js/custom.js"></script>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="../assets/plugins/mdl/material.min.js"></script>
<!-- END PAGE LEVEL SCRIPTS -->

</body>
</html>

grails-app/views/annonce/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
<g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<link rel="icon" type="image/x-icon" href="../assets/img/favicon.ico"/>
<link href="../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/plugins.css" rel="stylesheet" type="text/css" />
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
<!-- END GLOBAL MANDATORY STYLES -->

<!--  BEGIN CUSTOM STYLE FILE  -->
<link href="../assets/css/ecommerce/addedit_categories.css" rel="stylesheet" type="text/css">

<link rel="icon" type="image/x-icon" href="../assets/img/favicon.ico"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
<link href="../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/plugins.css" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->

<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="../assets/plugins/mdl/material.css">
</head>


<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Modification d'une annonce</h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area add-category">
                <div class="row">
                    <div class="mx-xl-auto col-xl-10 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Annonce</span></h2></div>

                            <div class="card-body">
                                <div class="card-body">
<g:form resource="${this.annonce}" method="PUT">
    <g:hiddenField name="version" value="${this.annonce?.version}" />

                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Title :</label>
                                                <div class="col-md-8">
                                                    <f:field class="form-control" bean="annonce" property="title" label=" " />
                                                </div>
                                            </div>
                                        </div>



                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Description :</label>
                                                <div class="col-md-8">
                                                    <f:field class="form-control" bean="annonce" property="description" label=" " />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Price :</label>
                                                <div class="col-md-8">
                                                    <f:field class="form-control" bean="annonce" property="price" label=" " />
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-xl-4 col-lg-6 col-sm-6  layout-spacing">
                                            <div class="statbox widget box box-shadow">

                                                <div class="widget-content widget-content-area">
                                                    <div class="mb-4">

                                                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">
                                                            <input type="hidden"  name="_status" />
                                                            <f:field class="form-control" bean="annonce" property="status" label=" " />
                                                            <span class="mdl-checkbox__label">Status</span>
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Author :</label>

                                                <div class="col-md-8">

                                                    <g:select class="form-control form-custom mb-4" name="author" from="${projet.grails.mbds.esatic.User.getAll()}" optionKey="id" optionValue="username"/>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group mb-4">
                                            <label for='illustrations'>Illustrations</label><ul></ul><a href="/illustration/create?annonce.id=">Ajouter une  Illustration</a>
                                        </div>
                                        <fieldset class="buttons">
                                            <input class="save" type="submit" value="Update" />
                                        </fieldset>
                                    </g:form>




                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="../assets/js/libs/jquery-3.1.1.min.js"></script>
<script src="../assets/js/loader.js"></script>
<script src="../assets/bootstrap/js/popper.min.js"></script>
<script src="../assets/bootstrap/js/bootstrap.min.js"></script>
<script src="../assets/plugins/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="../assets/plugins/blockui/jquery.blockUI.min.js"></script>
<script src="../assets/js/app.js"></script>

<script>
    $(document).ready(function() {
        App.init();
    });
</script>
<script src="../assets/js/custom.js"></script>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="../assets/plugins/mdl/material.min.js"></script>
<!-- END PAGE LEVEL SCRIPTS -->

</body>
</html>

grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>

<div class="row">

    <div class="col-xl-12 col-lg-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow driver-list br-4">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Liste des annonces</h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area p-0">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="form-check-column text-center">
                                <label for="driverListAll" class="new-control new-checkbox checkbox-primary pb-2">
                                    <input type="checkbox" id="driverListAll" class="new-control-input">

                                </label>
                            </th>
                            <th>Title</th>
                            <th class="text-center">Description</th>
                            <th class="text-center">Price Status</th>
                            <th class="text-center">Illustrations</th>
                            <th class="text-center">Price</th>

                            <th class="text-center">Author</th>
                            <th class="text-center">Actions</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <g:each in="${annonceList}" var="annonce">













                            <tr>
                                <td class="form-check-column text-center">
                                    <label class="new-control new-checkbox checkbox-primary pb-2">

                                    </label>
                                </td>
                                <td>

                                    <div class="d-inline-block">
                                        <span class="">


                                        </span>
                                        <div class=" mt-1 d-inline-block">
                                            <h6 class="mt-2 mb-0">${annonce.title}</h6>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center">${annonce.description}</td>
                                <td class="text-center"><div class="" data-toggle="tooltip" data-placement="top" title="" data-original-title="Available">${annonce.status}</div></td>
                                <td class="align-center"><g:each in="${annonce.illustrations}" var="illustration">
                                    <img src="${grailsApplication.config.assets.url + illustration.filename}"/>
                                </g:each>
                                </td>
                                <td class="align-center">${annonce.price}</td>
                                <td class="text-center">
                                    <span></span>
                                    <div class="t-d-rating">
                                        <i class=""><g:link controller="user" action="show" id="${annonce.author.id}">
                                            ${annonce.author.username}
                                        </g:link></i>

                                    </div>
                                </td>
                                <td>
                                    <g:link data-original-title="Modifier" controller="annonce" id="${annonce.id}" class="flaticon-edit bs-tooltip" action="edit" resource="${this.annonce}"></g:link>
                                    <g:form resource="${this.annonce}" method="DELETE">
                                        <input class="flaticon-delete  p-1 br-6 mb-1" type="submit" data-toggle="tooltip" data-placement="top" title="" data-original-title="Supprimer"

                                               value="${message(code: 'default.button.delete.label', default: 'Supprimer')}"
                                               onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Vous etes sure?')}');"/>

                                    </g:form>

                                </td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
</body>
</html>

grails-app/views/annonce/show.gsp
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta name="layout" content="main" />

</head>
<body>
<div class="row">
    <div class="btn-group  mb-4 mr-2">
        <button type="button" class="btn btn-success br-left-30">Action</button>
        <button type="button" class="btn btn-success br-right-30 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">

            <g:link class="dropdown-item" action="edit" resource="${this.annonce}"><g:message code="default.button.edit.label" default="modifier" /></g:link>

            <g:form resource="${this.annonce}" method="DELETE">
                <fieldset class="buttons">

                    <input class="dropdown-item" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
            <a class="dropdown-item" href="index">page d'acceuil</a>

        </div>
    </div>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Information de l'annonce</h4>
                    </div>
                </div>
            </div>

            <div class="widget-content widget-content-area add-sub-category">
                <div class="row">
                    <div class="mx-xl-auto col-xl-10 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Annonce</span></h2></div>
                            <div class="card-body">
                                <div class="card-body">

                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Title :</label>
                                            <div class="col-md-8">
                                                ${annonce.title}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Description:</label>
                                            <div class="col-md-8">
                                                ${annonce.description}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Price</label>
                                            <div class="col-md-8">
                                                ${annonce.price}

                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Status</label>
                                            <div class="col-md-8">
                                                ${annonce.status}


                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Illustration</label>
                                            <div class="col-md-8">

                                                <g:each in="${annonce.illustrations}" var="illustration">
                                                    <img src="${grailsApplication.config.assets.url + illustration.filename}"/>
                                                </g:each>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Author :</label>
                                            <div class="col-md-8">
                                                <g:link controller="user" action="show" id="${annonce.author.id}">
                                                    ${annonce.author.username}
                                                </g:link>

                                            </div>
                                        </div>
                                    </div>




                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>