grails-app/domain/projet/grails/mbds/esatic/User.groovy
package projet.grails.mbds.esatic

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [annonces: Annonce]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/projet/grails/mbds/esatic/UserController.groovy
package projet.grails.mbds.esatic

import grails.plugin.springsecurity.annotation.Secured

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured('ROLE_ADMIN')
class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]

    }


    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond ( new User(params), model: [roles:Role.list()] )
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond userService.get(id)
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />


    </head>
    <body>

    <div class="row"  id="create-user" role="main">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
            <div class="statbox widget box box-shadow" background-color="#004B8C">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Inscription des utlisateurs </h4>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area add-manage-product-2">
                    <div class="row">
                        <div class="col-xl-7 col-md-12">
                            <div class="card card-default">
                                <div class="card-heading"><h2 class="card-title"><span>Inscription</span></h2></div>
                                <div class="card-body">
                                    <div class="card-body">
                                      <g:form resource="${this.user}" class="form-horizontal"  method="POST">

                                            <div class="form-group mb-4">
                                                <div class="row">
                                                    <label class="col-md-4">Nom:</label>
                                                    <div class="col-md-8">
                                                        <input class="form-control" name="username" value="" required="" id="username"  type="text">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group mb-4">
                                                <div class="row">
                                                    <label class="col-md-4">Mot de passe:</label>
                                                    <div class="col-md-8">
                                                        <input class="form-control" type="password" name="password" required="" value="" id="password"  required=""  >
                                                    </div>
                                                </div>
                                            </div>



                                            <div class="form-group mb-4">
                                                <div class="row">
                                                    <label class="col-md-4">Role :</label>
                                                    <div class="col-md-8">
                                                        <g:select class="form-control form-custom mb-4" name="role" from="${roles}" optionKey="id" optionValue="authority"/>

                                                    </div>
                                                </div>
                                            </div>







                                          <div class="row">
                                              <div class="col-12 text-center  pb-4">
                                                  <button  name="create" class="save"
                                                           value="${message(code: 'default.button.create.label', default: 'Create') }">Enregistrer</button>
                                              </div>
                                          </div>

                                      </g:form>

                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-user" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.user}" method="PUT">
                <g:hiddenField name="version" value="${this.user?.version}" />
                <fieldset class="form">
                    <f:all bean="user"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />

</head>
<body>

<div class="row"  id="create-user" role="main">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow" background-color="#004B8C">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Modifier l'utlisateur </h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area add-manage-product-2">
                <div class="row">
                    <div class="col-xl-7 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Modification</span></h2></div>
                            <div class="card-body">
                                <div class="card-body">
                                    <g:form resource="${this.user}" class="form-horizontal"  method="PUT">

                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Nom:</label>
                                                <div class="col-md-8">
                                                    <f:field class="form-control" bean="user" property="username" label=" " />

                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Mot de passe:</label>
                                                <div class="col-md-8">
                                                    <f:field class="form-control" bean="user" property="password" label=" " />
                                                </div>
                                            </div>
                                        </div>



                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Role :</label>
                                                <div class="col-md-8">
                                                    <g:select class="form-control form-custom mb-4" name="role" from="${projet.grails.mbds.esatic.Role.getAll()}" optionKey="authority" optionValue="authority"/>

                                                </div>
                                            </div>
                                        </div>







                                        <div class="row">
                                            <div class="col-12 text-center  pb-4">
                                                <button  name="create" class="save"
                                                         value="${message(code: 'default.button.create.label', default: 'Create') }">Enregistrer</button>
                                            </div>
                                        </div>

                                    </g:form>

                                </div>

                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/user/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>

</head>
<body>



<div class="col-xl-15 col-lg-30 col-md-40 col-40 layout-spacing">

    <div class="row">
<g:each in="${userList}" var="user">

        <div class="col-sm-4 col-12 mb-sm-0 mb-4">
            <div class="widget-content-area social-likes text-center p-0  br-4">
                <div class="card facebook">
                    <div class="icon mb-4">
                        <i class="flaticon-facebook-logo"></i>
                    </div>
                    <div class="card-content">
                        <h5>${user.username}</h5>
                        
                    </div>
                    <div class="card-btn-section">
                        <p><g:link controller="user" action="show" id="${user.id}">voir details</g:link>
                        </p>
                    </div>
                </div>
            </div>
            <br>




        </div>
</g:each>
    </div>




    </div>
    <!--  END CONTENT PART  -->
</body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta name="layout" content="main" />

</head>
<body>
<div class="row">
    <div class="btn-group  mb-4 mr-2">
        <button type="button" class="btn btn-success br-left-30">Action</button>
        <button type="button" class="btn btn-success br-right-30 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">

            <g:link class="dropdown-item" action="edit" resource="${this.user}"><g:message code="default.button.edit.label" default="modifier" /></g:link>

            <g:form resource="${this.user}" method="DELETE">
                <fieldset class="buttons">

                    <input class="dropdown-item" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
            <a class="dropdown-item" href="index">page d'acceuil</a>

        </div>
    </div>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Information de l'utilisateur</h4>
                    </div>
                </div>
            </div>

            <div class="widget-content widget-content-area add-sub-category">
                <div class="row">
                    <div class="mx-xl-auto col-xl-10 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Information</span></h2></div>
                            <div class="card-body">
                                <div class="card-body">

                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-md-4">Username :</label>
                                                <div class="col-md-8">
                                                    ${user.username}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-md-4">Role :</label>
                                                <div class="col-md-8">
                                                    ${user.getAuthorities()*.authority.join(',')}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-md-4">Annonces :</label>
                                                <div class="col-md-8">
                                                 <g:each in="${user.annonces}" var="annonce">
                                                     <g:link controller="annonce" action="show" id="${annonce.id}">
                                                         ${annonce.title}
                                                     </g:link></br>
                                                 </g:each>

                                                </div>
                                            </div>
                                        </div>





                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>