grails-app/domain/projet/grails/mbds/esatic/Illustration.groovy
package projet.grails.mbds.esatic

class Illustration {
    /*
    Chemin pour accéder aux images via deux valeurs de configuration
    url = chemin externe (http://localhost:8081/assets/grails.svg)
    path = chemin interne (C:\Users\Utilisateur\IdeaProjects\projet-grails-mbds-esatic\grails-app\assets\images\grails.svg)
     */
    String filename

    static belongsTo = [annonce: Annonce]

    static constraints = {
        filename nullable: false, blank: false
    }
}

grails-app/controllers/projet/grails/mbds/esatic/IllustrationController.groovy
package projet.grails.mbds.esatic

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*


@Secured('ROLE_ADMIN')
class IllustrationController {

    IllustrationService illustrationService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 1000, 10000)
        respond illustrationService.list(params), model:[illustrationCount: illustrationService.count()]
    }

    def show(Long id) {
        respond illustrationService.get(id)
    }

    def create() {
        respond new Illustration(params)
    }

    def save(Illustration illustration) {
        if (illustration == null) {
            notFound()
            return
        }

        try {
            illustrationService.save(illustration)
        } catch (ValidationException e) {
            respond illustration.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'illustration.label', default: 'Illustration'), illustration.id])
                redirect illustration
            }
            '*' { respond illustration, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond illustrationService.get(id)
    }

    def update(Illustration illustration) {
        if (illustration == null) {
            notFound()
            return
        }

        try {
            illustrationService.save(illustration)
        } catch (ValidationException e) {
            respond illustration.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'illustration.label', default: 'Illustration'), illustration.id])
                redirect illustration
            }
            '*'{ respond illustration, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        illustrationService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'illustration.label', default: 'Illustration'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'illustration.label', default: 'Illustration'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/illustration/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />

</head>
<body>

<div class="row"  id="create-user" role="main">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow" background-color="#004B8C">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Inscription des illustrations </h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area add-manage-product-2">
                <div class="row">
                    <div class="col-xl-7 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Inscription</span></h2></div>
                            <div class="card-body">
                                <div class="card-body">
                                    <g:form resource="${this.illustration}" class="form-horizontal"  method="POST">


                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Filename:</label>
                                                <div class="widget-content widget-content-area">




                                                        <f:field bean="illustration" property="filename" label=" "/>






                                                </div>
                                            </div>
                                        </div>




                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Annonces:</label>

                                                <div class="col-md-8">
                                                    <f:field bean="illustration" property="annonce" label=" "/>
                                                </div>
                                            </div>
                                        </div>







                                        <div class="row">
                                            <div class="col-12 text-center  pb-4">
                                                <button  name="create" class="save"
                                                         value="${message(code: 'default.button.create.label', default: 'Create') }">Enregistrer</button>
                                            </div>
                                        </div>

                                    </g:form>

                                </div>

                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/illustration/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />

</head>
<body>

<div class="row"  id="create-user" role="main">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow" background-color="#004B8C">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Modification des illustrations </h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area add-manage-product-2">
                <div class="row">
                    <div class="col-xl-7 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Modification</span></h2></div>
                            <div class="card-body">
                                <div class="card-body">
                                    <g:form resource="${this.illustration}" method="PUT">
                                        <g:hiddenField name="version" value="${this.illustration?.version}" />


                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Filename:</label>
                                                <div class="widget-content widget-content-area">




                                                    <f:field bean="illustration" property="filename" label=" "/>






                                                </div>
                                            </div>
                                        </div>




                                        <div class="form-group mb-4">
                                            <div class="row">
                                                <label class="col-md-4">Annonces:</label>

                                                <div class="col-md-8">
                                                    <f:field bean="illustration" property="annonce" label=" "/>
                                                </div>
                                            </div>
                                        </div>







                                        <div class="row">
                                            <div class="col-12 text-center  pb-4">
                                                <button  name="create" class="save"
                                                         value="${message(code: 'default.button.create.label', default: 'Create') }">Enregistrer</button>
                                            </div>
                                        </div>

                                    </g:form>

                                </div>

                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/illustration/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'illustration.label', default: 'Illustration')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
        <ul class="navbar-nav flex-row mr-auto">

            <li class="nav-item d-lg-block d-none">
                <form class="form-inline form-inline search animated-search" role="search">
                    <i class="flaticon-search-1 d-lg-none d-block"></i>
                    <input type="text" class="form-control search-form-control" placeholder="Search here...">
                </form>
            </li>
        </ul>
    </head>
    <body>

    <div class="row layout-spacing">
        <div class="col-lg-12">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Liste</h4>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area">
                    <div class="table-responsive mb-4">
                        <table id="customer-info-detail-3" class="table style-3 table-bordered  table-hover">
                            <thead>
                            <tr>
                                <th class="checkbox-column text-center"> Numéro </th>
                                <th class="align-center">Filename</th>
                                <th>Annonce</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                           <g:each in="${illustrationList}" var="illustration">
                            <tr>
                                <td class="checkbox-column text-center">${illustration.id} </td>
                                <td class="align-center">
                                    <span>
                                        <img src="${grailsApplication.config.assets.url + illustration.filename}"/>
                                    </span>
                                </td>

                                <td class="align-center"><span class="shadow-none badge badge-success">
                                    ${illustration.annonce.description}
                                </span></td>
                                <td class="text-center">
                                    <ul class="table-controls">
                                        <g:link data-original-title="Modifier" controller="illustration" id="${illustration.id}" class="flaticon-edit bs-tooltip" action="edit" resource="${this.illustration}"></g:link>
                                        <g:form resource="${this.illustration}" method="DELETE">
                                            <input class="flaticon-delete  p-1 br-6 mb-1" type="submit" data-toggle="tooltip" data-placement="top" title="" data-original-title="Supprimer"

                                                   value="${message(code: 'default.button.delete.label', default: 'Supprimer')}"
                                                   onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Vous etes sure?')}');"/>

                                        </g:form>

                                    </ul>
                                </td>
                            </tr>



                          </g:each>


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="../assets/js/libs/jquery-3.1.1.min.js"></script>
    <script src="../assets/js/loader.js"></script>
    <script src="../assets/bootstrap/js/popper.min.js"></script>
    <script src="../assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="../assets/plugins/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="../assets/js/app.js"></script>

    <script>
        $(document).ready(function() {
            App.init();
        });
    </script>
    <script src="../assets/js/custom.js"></script>
    <!-- END GLOBAL MANDATORY SCRIPTS -->

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="../assets/plugins/table/datatable/datatables.js"></script>
    <script>
        // var e;
        c1 = $('#customer-info-detail-1').DataTable({
            "lengthMenu": [ 5, 10, 20, 50, 100 ],
            headerCallback:function(e, a, t, n, s) {
                e.getElementsByTagName("th")[0].innerHTML='<label class="new-control new-checkbox checkbox-outline-primary m-auto">\n<input type="checkbox" class="new-control-input chk-parent select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
            },
            columnDefs:[ {
                targets:0, width:"30px", className:"", orderable:!1, render:function(e, a, t, n) {
                    return'<label class="new-control new-checkbox checkbox-outline-primary  m-auto">\n<input type="checkbox" class="new-control-input child-chk select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
                }
            }],
            "language": {
                "paginate": {
                    "previous": "<i class='flaticon-arrow-left-1'></i>",
                    "next": "<i class='flaticon-arrow-right'></i>"
                },
                "info": "Showing page _PAGE_ of _PAGES_"
            }
        });

        multiCheck(c1);

        c2 = $('#customer-info-detail-2').DataTable({
            "lengthMenu": [ 5, 10, 20, 50, 100 ],
            headerCallback:function(e, a, t, n, s) {
                e.getElementsByTagName("th")[0].innerHTML='<label class="new-control new-checkbox checkbox-outline-primary m-auto">\n<input type="checkbox" class="new-control-input chk-parent select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
            },
            columnDefs:[ {
                targets:0, width:"30px", className:"", orderable:!1, render:function(e, a, t, n) {
                    return'<label class="new-control new-checkbox checkbox-outline-primary  m-auto">\n<input type="checkbox" class="new-control-input child-chk select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
                }
            }],
            "language": {
                "paginate": {
                    "previous": "<i class='flaticon-arrow-left-1'></i>",
                    "next": "<i class='flaticon-arrow-right'></i>"
                },
                "info": "Showing page _PAGE_ of _PAGES_"
            }
        });

        multiCheck(c2);

        c3 = $('#customer-info-detail-3').DataTable({
            "lengthMenu": [ 5, 10, 20, 50, 100 ],
            "language": {
                "paginate": {
                    "previous": "<i class='flaticon-arrow-left-1'></i>",
                    "next": "<i class='flaticon-arrow-right'></i>"
                },
                "info": "Showing page _PAGE_ of _PAGES_"
            }
        });

        multiCheck(c3);
    </script>
    <!-- END PAGE LEVEL SCRIPTS -->

    </body>
</html>

grails-app/views/illustration/show.gsp
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta name="layout" content="main" />

</head>
<body>
<div class="row">
    <div class="btn-group  mb-4 mr-2">
        <button type="button" class="btn btn-success br-left-30">Action</button>
        <button type="button" class="btn btn-success br-right-30 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">

            <g:link class="dropdown-item" action="edit" resource="${this.illustration}"><g:message code="default.button.edit.label" default="modifier" /></g:link>

            <g:form resource="${this.illusration}" method="DELETE">
                <fieldset class="buttons">

                    <input class="dropdown-item" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
            <a class="dropdown-item" href="index">page d'acceuil</a>

        </div>
    </div>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Information de l'illustration</h4>
                    </div>
                </div>
            </div>

            <div class="widget-content widget-content-area add-sub-category">
                <div class="row">
                    <div class="mx-xl-auto col-xl-10 col-md-12">
                        <div class="card card-default">
                            <div class="card-heading"><h2 class="card-title"><span>Information</span></h2></div>
                            <div class="card-body">
                                <div class="card-body">

                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Filename :</label>
                                            <div class="col-md-8">
                                                ${illustration.filename}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-4">Annonces :</label>
                                            <div class="col-md-8">
                                                <g:link controller="annonce" action="show" id="${illustration.annonce.id}">
                                                    ${illustration.annonce.title}
                                                </g:link>

                                            </div>
                                        </div>
                                    </div>





                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>